<!DOCTYPE html>
<html lang="en">
<head>
<title>ESKO CONSTRUCTION</title>
<meta charset="UTF-8"> 
    <meta https-equipv="x-UA-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <<img src="IMAGES/logo2.jpg" alt="Esko Construction Logo" height="30px"width="30px">
<a class="navbar-brand" href="#">ESKO CONSTRUCTIONS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#Contact us">Contact <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#EMAIL">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          PROJECTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#NTER STATE">ROAD CONSTRUCTIONS</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#HOUSES AND HOTELS">BUILDING CONSTRUCTIONS</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#OVER">BRIDGE CONSTRUCTIONS</a>
          
        </div>
      
  </div>
</nav>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="IMAGES/br1.jpg" alt="BRIDGE">
      <H3>BRIDGES</H3>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="IMAGES/br2.jpg" alt="ROAD">
      <H3>ROADS</H3>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="IMAGES/br3.jpg" alt="buildings">
      <h3>BUILDINGS</H3>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<a id="INTER STATE">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">ROADS</H2>
</div>
<div class="container-fluid">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/RC4.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/EK9.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/RC3.jpg" class="img-fluid pb-2">
</div>
</div>
</div>
</section>
<a id="HOUSES AND HOTELS">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">BUILDINGS</H2>
</div>
<section>
  <div align="center">
    <iframe  width="860" height="615" src="./IMAGES/site.mp4" frameborder="0" allowfullscreen></iframe>
  </div>
</section>
<div class="container-fluid"id="image-container">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/EK5.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/EK4.jpg" class="img-fluid pb-2">
</div>

<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/EK6.jpg" class="img-fluid pb-2">
 
<section class="my-4">
    <div class="py-4">

</div>
</div>
</div>
</div>
</div>
</div>
</section>


<a id="OVER">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">BRIDGES</H2>
</div>
<div class="container-fluid">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/BC1.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/BC2.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/BC4.jpg" class="img-fluid pb-2">
</div>
</div>
</div>

</section>


<a id="Contact us">
<section class="my-4">
    <div class="py-4">
<h2 class="text-center">Contact Us</h2>
</div>
<div class="w-50 m-auto">
    <form action="about.php method="post">
        <div class="form-group">
            <label>NAME:</label>
            <input type="text" name="NAME" class="form-control">
</div>
</a>
<a id="EMAIL">
<div class="form-group">
            <label>Email:</label>
            <input type="email" name="email" class="form-control">
</div>
<div class="form-group">
            <label>NUMBER:</label>
            <input type="text" name="NUMBER" class="form-control">
</div>
</a>
<a id="Submit">
<button type="submit" class="btn-success">submit</button>
</form>
</div>
</section>
<section class="my-4">
    <div class="py-4">
<a id="about">
<h2 class="text-center">About</h2>
</div>
</a>
<div class="container-fluid">
<h3 class="text-center">ESKO CONSTRUCTIONS</h3> <br>
<p class="text-center"><b>Esko Constructions: Building Dreams, Delivering Excellence. Quality craftsmanship, timely delivery, and customer satisfaction – our pillars of success. Your vision, our commitment.</b></p>

</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
</body>
</body>
</html>