<!DOCTYPE html>
<html lang="en">
<head>
<title>NigerianTribes</title>
    <meta charset="UTF-8"> 
    <meta https-equipv="x-UA-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">NigerianTribes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#Contact us">Contact <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#EMAIL">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          TRIBES
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#NDIIGBO">IGBO</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#ODUDUWA">YORUBA</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#AREWA">HAUSA</a>
          <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="#OILMONEY">SOUTHERN</a>
         
        </div>
      
  </div>
</nav>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="IMAGES/ie1.jpg" alt="IGBO">
      <H3>IGBO TRIBE</H3>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="IMAGES/nm1.jpg" alt="HAUSA">
      <H3>HAUSA TRIBE</H3>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="IMAGES/ym1.jpg" alt="YORUBA">
      <h3>YORUBA TRIBE</H3>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<a id="NDIIGBO">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">IGBO</H2>
</div>
<div class="container-fluid">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/im1.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/im2.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/im3.jpg" class="img-fluid pb-2">
</div>
</div>
</div>

</section>
<a id="ODUDUWA">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">YORUBA</H2>
</div>
<div class="container-fluid">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/ym4.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/ym 2.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/ym3.jpg" class="img-fluid pb-2">
</div>
</div>
</div>
</section>
<a id="AREWA">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">HAUSA</H2>
</div>
<div class="container-fluid">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/nm4.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/nm2.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/nm3.jpg" class="img-fluid pb-2">
</div>
</div>
</div>
</section>
<a id="OILMONEY">
<section class="my-4">
    <div class="py-4">
          <h2 class="text-center">SOUTHERN</H2>
          <P><BR> This is mostly populated with the Urhobo, Itsekiri and Ijaw speaking tribes of southern nigeria before Niger River in delta state</p></BR>
</div>
<SECTION>
<div class="container-fluid">
  <div class="row">
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/UM6.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/UM2.jpg" class="img-fluid pb-2">
</div>
<div class="col-lg-4 col-md-4 col-12">
  <IMG src="IMAGES/UM3.jpg" class="img-fluid pb-2">
</div>
</div>
</div>
</section>
<a id="Contact us">
<section class="my-4">
    <div class="py-4">
<h2 class="text-center">Contact Us</h2>
</div>
<div class="w-50 m-auto">
    <form action="about.php method="post">
        <div class="form-group">
            <label>NAME:</label>
            <input type="text" name="NAME" class="form-control">
</div>
</a>
<a id="EMAIL">
<div class="form-group">
            <label>Email:</label>
            <input type="email" name="email" class="form-control">
</div>
<div class="form-group">
            <label>NUMBER:</label>
            <input type="text" name="NUMBER" class="form-control">
</div>
</a>
<a id="Submit">
<button type="submit" class="btn-success">submit</button>
</form>
</div>
</section>
<section class="my-4">
    <div class="py-4">
<a id="about">
<h2 class="text-center">About</h2>
</div>
</a>
<div class="container-fluid">
<h3 class="text-center">IKECHUKWU</h3> <br>
<p class="text-center"><b> i am a freelance photogragher interested in culture and regional photography and i have an experience of 4 years.</b></p>

</section>

 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
</body>
</html>